config/routes.rb
Rails.application.routes.draw do
  devise_for :authors
  resources :wiki_posts
  resources :authors, only: [:index, :show, :destroy]

  namespace :welcome do
    get 'index'
    get 'about'
  end

  get '/about', to: 'welcome#about'
  get "up" => "rails/health#show", as: :rails_health_check
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :wiki_posts
    validates :name, :email, presence: true
    validates :email, uniqueness: true
end

app/models/wiki_post.rb
class WikiPost < ApplicationRecord
  has_one_attached :image
  belongs_to :author
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation, :current_password])
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  # def new
  #   @author = Author.new
  # end

  # GET /authors/1/edit
  # def edit
  # end

  # POST /authors or /authors.json
  # def create
  #   @author = Author.new(author_params)

  #   respond_to do |format|
  #     if @author.save
  #       format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
  #       format.json { render :show, status: :created, location: @author }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @author.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /authors/1 or /authors/1.json
  # def update
  #   respond_to do |format|
  #     if @author.update(author_params)
  #       format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
  #       format.json { render :show, status: :ok, location: @author }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @author.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def author_params
    #   params.require(:author).permit(:name, :email, :password)
    # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    @contributers = Author.all
    
  end
end

app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ show edit update destroy ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy!

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_post
      @wiki_post = WikiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_post_params
      params.require(:wiki_post).permit(:title, :description, :author_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= author.email %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  | <%= link_to "Back to authors", authors_path %> |
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= author.created_at.strftime('%B %d, %Y') %></td>
        <td><%= author.updated_at.strftime('%B %d, %Y') %></td>
        <td>
          | <%= link_to 'View', author_path(author) %> |
          <%= link_to 'Delete', author, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{author.name}?" } %> |
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


| <%= link_to "New author", new_author_registration_path %> |

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  | <%= link_to "Back to authors", authors_path %> |
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<ul>
  <% @author.wiki_posts.each do |post| %>
    <li><%= link_to post.title, wiki_post_path(post) %></li>
  <% end %>
<ul>

<div>
  | <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Destroy this author", @author, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{@author.name}?" } %> |
  <%= link_to "Back to authors", authors_path %> |
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= javascript_importmap_tags %>
  <%= turbo_include_tags %>
  <head>
    <title>Wiki</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <nav>
    <ul>
      | <%= link_to 'Authors', authors_path %> |
      <%= link_to 'Wiki Posts', wiki_posts_path %> |
      <span></span>
      <%= link_to 'Home', root_path %> |
      <%= link_to 'About', welcome_about_path %> |
      <%= link_to 'Edit Profile', edit_author_registration_path %> |
      <%= link_to 'Sign Out', destroy_author_session_path, data: { turbo_method: :delete } %> |
    </ul>
  </nav>
</header>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Wiki</h1>
<h2>Site Contributers</h2>
<ul>
  <% @contributers.each do |contributer| %>
    <li> <%= '> ' + contributer.name %></li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1>Wiki</h1>

<% if author_signed_in? %>
  <h1>Welcome, <%= current_author.name %></h1>
<% else %>
  <h1>Home</h1>
  <%= link_to 'Sign in', new_author_session_path %>
  <%= link_to 'Sign Up', new_author_registration_path %>
<% end %>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.select :author_id, Author.all.collect { |a| [ a.name, a.id ] }, {prompt: 'Select Person'} %>
  </div>

  <div>
  <%= form.label :image, style: "display: block" %>
  <%= form.file_field :image %>
</div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
  <p>
    <strong>Title:</strong>
    <%= wiki_post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= wiki_post.description %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= wiki_post.author_id %>
  </p>

</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  | <%= link_to "Back to wiki posts", wiki_posts_path %> |
</div>

app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wiki posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Description</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @wiki_posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.author.name %></td>
        <td><%= post.description %></td>
        <td><%= post.created_at.strftime('%B %d, %Y') %></td>
        <td><%= post.updated_at.strftime('%B %d, %Y') %></td>
        <td>
          | <%= link_to 'View', wiki_post_path(post) %> |
          <%= link_to 'Edit', edit_wiki_post_path(post) %> |
          <%= link_to 'Delete', post, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{post.title}?" } %> |
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

| <%= link_to "New wiki post", new_wiki_post_path %> |

app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  | <%= link_to "Back to wiki posts", wiki_posts_path %> |
</div>

app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @wiki_post.title.titleize %></h1>
<p>Created on <%= @wiki_post.created_at.strftime('%B %d, %Y') %></p>
<p>Description: <%= @wiki_post.description %></p>

<% if @wiki_post.image.attached? %>
  <%= image_tag @wiki_post.image %>
<% end %>

<p>Author: <%=link_to @wiki_post.author.name.titleize, author_path(@wiki_post.author)%><p>

<div>
  | <%= link_to "Edit this wiki post", edit_wiki_post_path(@wiki_post) %> |
  <%= link_to "Destroy this author", @wiki_post, data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete post #{@wiki_post.title}?" } %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %> |
</div>